backend:
  name: github
  repo: rossmaryrangel/Mary-website
  branch: main # Branch to update (optional; defaults to master)
  site_domain: https://rossmaryrangel.com
  base_url: https://rossmaryrangel.com
  auth_endpoint: /api/auth

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "agenda"
    label: "Agendas"
    folder: "content/agenda"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title",   name: "title", widget: "string" }
      - { label: "Date",    name: "date",  widget: "datetime" }
      - { label: "Body",    name: "body",  widget: "markdown" }